import { createFileRoute, Link } from "@tanstack/react-router";
import { Target, Users, Lock, ArrowRight, ShieldCheck, Stethoscope } from "lucide-react";
import { MarketingLayout } from "@/components/marketing/MarketingLayout";
import { Eyebrow, SectionHeading } from "@/components/premium/SectionHeading";
import { PremiumButton } from "@/components/premium/PremiumButton";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [
      { title: "Architecture & Philosophy — InsightForge Healthcare & Education RAG" },
      {
        name: "description",
        content:
          "Cited RAG document intelligence for medical guidelines, PubMed studies, and university curricula with zero data leakage.",
      },
    ],
  }),
  component: AboutPage,
});

const pillars = [
  {
    icon: Stethoscope,
    title: "Clinical & Evidence Rigor",
    body: "Medical answers must be grounded in verified guidelines and clinical trial papers with explicit page citations.",
  },
  {
    icon: Users,
    title: "Designed for Clinicians & Educators",
    body: "Doctors, medical researchers, professors, and students share a unified RAG document context.",
  },
  {
    icon: Lock,
    title: "100% HIPAA & FERPA Privacy",
    body: "Local FAISS vector store running directly on disk with zero third-party cloud data leakage.",
  },
];

const sections = [
  {
    eyebrow: "OUR MISSION",
    title: "Empowering Healthcare & Education with Cited RAG AI.",
    body: "Medical guidelines and academic literature expand by thousands of pages daily. We built InsightForge Health & Edu RAG to instantly retrieve precise clinical evidence from 100-page PDFs and EMR datasets.",
  },
  {
    eyebrow: "GROUND-TRUTH PHILOSOPHY",
    title: "Zero hallucination. Page & paragraph citations.",
    body: "Every clinical summary generated by our Vault RAG pipeline cites exact vector chunks retrieved from PubMed PDFs or FDA drug protocols.",
  },
  {
    eyebrow: "DATA PRIVACY & SOVEREIGNTY",
    title: "Air-gapped local FAISS vector architecture.",
    body: "Sentence-transformers embeddings and vector calculations run locally on your institution's infrastructure, guaranteeing total patient and student privacy.",
  },
];

function AboutPage() {
  return (
    <MarketingLayout>
      <section className="bg-canvas section-rhythm border-b border-hairline">
        <div className="mx-auto max-w-5xl px-6 text-center">
          <Eyebrow className="justify-center">HEALTHCARE & EDUCATION MISSION</Eyebrow>
          <h1 className="display-lg text-ink mt-4 font-normal">
            Trustworthy, cited RAG AI for medicine & learning.
          </h1>
          <p className="body-md text-body max-w-2xl mx-auto mt-4">
            Connecting statistical vital anomaly signals with dense FAISS vector document retrieval across clinical guidelines and course materials.
          </p>
        </div>
      </section>

      <section className="bg-canvas section-rhythm border-b border-hairline">
        <div className="mx-auto max-w-7xl px-6">
          <div className="grid gap-6 md:grid-cols-3">
            {pillars.map((p) => {
              const Icon = p.icon;
              return (
                <div key={p.title} className="bg-surface-soft border border-hairline rounded-lg p-8">
                  <div className="flex h-10 w-10 items-center justify-center rounded-md bg-canvas border border-hairline text-[#1b61c9]">
                    <Icon className="h-5 w-5" />
                  </div>
                  <h3 className="title-md text-ink mt-6 font-semibold">{p.title}</h3>
                  <p className="body-md text-body mt-3">{p.body}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      <section className="bg-canvas section-rhythm border-b border-hairline">
        <div className="mx-auto max-w-4xl px-6 flex flex-col gap-16">
          {sections.map((s) => (
            <div key={s.title}>
              <Eyebrow>{s.eyebrow}</Eyebrow>
              <h2 className="display-md text-ink mt-3 font-normal">{s.title}</h2>
              <p className="body-md text-body mt-4">{s.body}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="bg-canvas section-rhythm">
        <div className="mx-auto max-w-5xl px-6 text-center">
          <div className="bg-surface-strong rounded-lg p-12">
            <SectionHeading
              align="center"
              eyebrow="GET STARTED"
              title="Launch the Clinical & Educational Workspace."
              description="Upload your medical PDFs or lab datasets and query RAG evidence today."
            />
            <div className="mt-8 flex justify-center gap-4">
              <Link to="/app/dashboard">
                <PremiumButton variant="primary" size="lg">
                  Launch Clinical Cockpit <ArrowRight className="ml-2 h-4 w-4" />
                </PremiumButton>
              </Link>
            </div>
          </div>
        </div>
      </section>
    </MarketingLayout>
  );
}