import { createFileRoute, Link } from "@tanstack/react-router";
import { Target, Users, Lock, ArrowRight, ShieldCheck, Stethoscope, Sparkles, LayoutDashboard, Database, Cpu } from "lucide-react";
import { MarketingLayout } from "@/components/marketing/MarketingLayout";
import { GlowBadge } from "@/components/premium/GlowBadge";
import { PremiumButton } from "@/components/premium/PremiumButton";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [
      { title: "Architecture & Philosophy — InsightForge Healthcare & Education RAG" },
      {
        name: "description",
        content:
          "Cited RAG document intelligence for medical guidelines, PubMed studies, and university curricula with zero data leakage.",
      },
    ],
  }),
  component: AboutPage,
});

const pillars = [
  {
    icon: Stethoscope,
    title: "Clinical & Evidence Rigor",
    body: "Medical answers must be grounded in verified guidelines and clinical trial papers with explicit page and paragraph citations.",
    badge: "EVIDENCE CITED",
  },
  {
    icon: Users,
    title: "Designed for Clinicians & Educators",
    body: "Doctors, medical researchers, professors, and students share a unified RAG document context with multi-user isolation.",
    badge: "MULTI-ROLE RAG",
  },
  {
    icon: Lock,
    title: "100% HIPAA & FERPA Privacy",
    body: "Local FAISS vector store running directly on disk with zero third-party cloud data leakage or external tracking.",
    badge: "AIR-GAPPED FAISS",
  },
];

const sections = [
  {
    icon: Target,
    eyebrow: "OUR MISSION",
    title: "Empowering Healthcare & Education with Cited RAG AI.",
    body: "Medical guidelines and academic literature expand by thousands of pages daily. We built InsightForge Health & Edu RAG to instantly retrieve precise clinical evidence from 100-page PDFs and EMR datasets.",
  },
  {
    icon: ShieldCheck,
    eyebrow: "GROUND-TRUTH PHILOSOPHY",
    title: "Zero hallucination. Page & paragraph citations.",
    body: "Every clinical summary generated by our Vault RAG pipeline cites exact vector chunks retrieved from PubMed PDFs or FDA drug protocols.",
  },
  {
    icon: Cpu,
    eyebrow: "DATA PRIVACY & SOVEREIGNTY",
    title: "Air-gapped local FAISS vector architecture.",
    body: "Sentence-transformers embeddings and vector calculations run locally on your institution's infrastructure, guaranteeing total patient and student privacy.",
  },
];

function AboutPage() {
  return (
    <MarketingLayout>
      {/* PAGE HERO HEADER */}
      <section className="bg-[var(--canvas)] py-14 md:py-20 border-b border-[var(--hairline)] transition-colors duration-300">
        <div className="mx-auto max-w-4xl px-6 text-center">
          <GlowBadge variant="mint">HEALTHCARE & EDUCATION MISSION</GlowBadge>
          <h1 className="text-4xl sm:text-5xl font-display font-normal text-[var(--ink)] mt-4 leading-tight">
            Trustworthy, cited RAG AI for medicine & learning.
          </h1>
          <p className="body-lg text-[var(--muted)] max-w-2xl mx-auto mt-4 text-base sm:text-lg">
            Connecting statistical vital anomaly signals with dense FAISS vector document retrieval across clinical guidelines and course materials.
          </p>
        </div>
      </section>

      {/* CORE PILLARS GRID */}
      <section className="bg-[var(--canvas)] py-16 md:py-24 border-b border-[var(--hairline)] transition-colors duration-300">
        <div className="mx-auto max-w-7xl px-8">
          <div className="grid gap-8 md:grid-cols-3">
            {pillars.map((p) => {
              const Icon = p.icon;
              return (
                <div
                  key={p.title}
                  className="bg-[var(--surface-card)] border border-[var(--hairline)] rounded-2xl p-8 shadow-md flex flex-col justify-between transition-all duration-300 hover:border-[#c1fbd4]"
                >
                  <div>
                    <div className="flex items-center justify-between mb-6">
                      <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-[var(--surface-soft)] border border-[var(--hairline)] text-[#c1fbd4]">
                        <Icon className="h-6 w-6" />
                      </div>
                      <GlowBadge variant="shade">{p.badge}</GlowBadge>
                    </div>
                    <h3 className="heading-lg text-[var(--ink)] font-normal">{p.title}</h3>
                    <p className="body-md text-[var(--muted)] mt-3 leading-relaxed">{p.body}</p>
                  </div>

                  <div className="mt-8 pt-4 border-t border-[var(--hairline)] flex items-center justify-between text-xs font-mono text-[#c1fbd4]">
                    <span>ARCHITECTURE PILLAR</span>
                    <ShieldCheck className="h-4 w-4" />
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* DETAILED PHILOSOPHY & ARCHITECTURE SECTIONS */}
      <section className="bg-[var(--surface-soft)] py-16 md:py-24 border-b border-[var(--hairline)] transition-colors duration-300">
        <div className="mx-auto max-w-5xl px-8 flex flex-col gap-16">
          {sections.map((s) => {
            const Icon = s.icon;
            return (
              <div
                key={s.title}
                className="bg-[var(--surface-card)] border border-[var(--hairline)] rounded-2xl p-8 md:p-10 shadow-lg grid md:grid-cols-12 gap-6 items-start"
              >
                <div className="md:col-span-2 flex h-14 w-14 items-center justify-center rounded-xl bg-[var(--surface-soft)] border border-[var(--hairline)] text-[#c1fbd4]">
                  <Icon className="h-7 w-7" />
                </div>
                <div className="md:col-span-10">
                  <span className="caption uppercase font-semibold text-[#c1fbd4] tracking-wider">{s.eyebrow}</span>
                  <h2 className="text-2xl sm:text-3xl font-display font-normal text-[var(--ink)] mt-2 leading-snug">{s.title}</h2>
                  <p className="body-md text-[var(--body)] mt-3 leading-relaxed text-base">{s.body}</p>
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* CALL TO ACTION BANNER */}
      <section className="bg-[var(--canvas)] py-16 md:py-20 transition-colors duration-300">
        <div className="mx-auto max-w-4xl px-8 text-center">
          <div className="bg-[var(--surface-card)] border border-[var(--hairline)] rounded-2xl p-10 md:p-14 shadow-xl">
            <GlowBadge variant="mint" className="mb-4">SYSTEM ARCHITECTURE READY</GlowBadge>
            <h2 className="text-3xl sm:text-4xl font-display font-normal text-[var(--ink)]">
              Launch the Clinical & Educational Workspace.
            </h2>
            <p className="body-md text-[var(--muted)] max-w-xl mx-auto mt-3">
              Upload your medical PDFs or lab datasets and query RAG evidence today.
            </p>
            <div className="mt-8 flex flex-wrap justify-center gap-4">
              <Link to="/app/dashboard">
                <PremiumButton variant="primaryPill" size="lg">
                  <LayoutDashboard className="h-4 w-4 mr-1" /> Launch Workspace <ArrowRight className="ml-1 h-4 w-4" />
                </PremiumButton>
              </Link>
              <Link to="/app/query">
                <PremiumButton variant="outlineOnDark" size="lg">
                  <Sparkles className="h-4 w-4 mr-1 text-[#c1fbd4]" /> Open RAG Search
                </PremiumButton>
              </Link>
            </div>
          </div>
        </div>
      </section>
    </MarketingLayout>
  );
}